### ISSUE TITLE
図5.2を描くコードがない

### ISSUE THREAD

**Issue by nakamichiworks** [MatsuuraKentaro/RStanBook#2]
勉強させていただいております。

本編の図5.2（p. 61）を描くためのコード（`chap05/fig5-2.R`？）がないようなのですが，コミットし忘れでしょうか？

**Comment by MatsuuraKentaro** [comment]
この図はあまり広めたくないのであえてコードをアップしておらずすみません。宿題にはよいかもしれません。Stanファイルもいじって、A=0と1のそれぞれの場合で予測分布を算出しておくとR側での計算がラクです。

**Comment by nakamichiworks** [comment]
意図的に上げていなかったのですね．了解しました．
