### ISSUE TITLE
エクササイズ6.4. のヒント「一番下段の左」は上段の左？

### ISSUE THREAD

**Issue by 3100** [MatsuuraKentaro/RStanBook#3]
素晴らしい本を翻訳してくださり、大変感謝しています。
表題に関して、原著では`upper-left panel`とあるので、上段の左ではないかと思いますが、いかがでしょうか。

**Comment by 3100** [comment]
申し訳ありません。投稿先を間違えました。

**Comment by MatsuuraKentaro** [comment]
本日サポートサイトができて、URLは以下のようです。作成中のようですが、issueはopenできると思います。
https://github.com/kazutan/DBDA2E-ja

**Comment by 3100** [comment]
@MatsuuraKentaro ありがとうございます。お教えいただいた先でイシューを立て直しました。

**Comment by kazutan** [comment]
@MatsuuraKentaro お手数をお掛けしました。ありがとうございました。
