### ISSUE TITLE
図5.2のデータYの値について

### ISSUE THREAD

**Issue by gyoonishi** [MatsuuraKentaro/RStanBook#4]
質問はここで大丈夫ですか？

p.49の図5.2（`chap05/output/fig5-2.png`）のデータYの値が最大で0.6程度あるのですが、
`input/data-attendance-1.txt` を確認するとYの最大値は0.423でした。
図が間違っているのでしょうか？

**Comment by MatsuuraKentaro** [comment]
ここで大丈夫です！図5.2の方が間違っています。すみません。あとで差し替えます。ありがとうございました。

**Comment by MatsuuraKentaro** [comment]
差し替えました。正誤表にも追加しました。ご迷惑おかけしました。
https://github.com/MatsuuraKentaro/RStanBook/blob/master/errata.md
