### ISSUE TITLE
p205、model11-1.stanがうまく働かない

### ISSUE THREAD

**Issue by takeshou** [MatsuuraKentaro/RStanBook#5]
p205のmodel11-1.stanについて質問させてください。
テキストとGitHubのコードの通りmodel11-1.stanを利用しようとすると、log(0)の計算が含まれるようで、下記のエラーがでてしまいます。

Rejecting initial value:
 Log probability evaluates to log(0), i.e. negative infinity.
 Stan can't start sampling from this initial value.

同僚が作成してくれた下のコードのようにlog(0)を回避すると動くようですが、何かシンプルな方法はありますでしょうか？

```stan
data {
    int N;
    int<lower=0, upper=1> Y[N];
}

parameters {
    real<lower=0.01, upper=0.9> q;
}

model {
  
    for (n in 1:N){
        if(Y[n] == 0){
            target += bernoulli_lpmf(Y[n] | q); 
        }else{
            target += log_sum_exp(log(0.5) + bernoulli_lpmf(Y[n] | q), log(0.5) + bernoulli_lpmf(Y[n] | 1));
        }
    }
}
```

なお、sessionInfo()で確かめた実行環境は以下の通りです。

R version 3.5.1 (2018-07-02)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 17763)

Matrix products: default

locale:
[1] LC_COLLATE=Japanese_Japan.932  LC_CTYPE=Japanese_Japan.932
[3] LC_MONETARY=Japanese_Japan.932 LC_NUMERIC=C
[5] LC_TIME=Japanese_Japan.932

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] rstan_2.17.3       StanHeaders_2.17.2 ggplot2_3.0.0

loaded via a namespace (and not attached):
[1] Rcpp_0.12.18     withr_2.1.2      crayon_1.3.4     dplyr_0.7.6
[5] assertthat_0.2.0 grid_3.5.1       plyr_1.8.4       R6_2.2.2
[9] gtable_0.2.0     stats4_3.5.1     magrittr_1.5     scales_1.0.0
[13] pillar_1.3.0     rlang_0.2.2      lazyeval_0.2.1   bindrcpp_0.2.2
[17] glue_1.3.0       purrr_0.2.5      munsell_0.5.0    compiler_3.5.1
[21] inline_0.3.15    pkgconfig_2.0.2  colorspace_1.3-2 tidyselect_0.2.4
[25] bindr_0.1.1      gridExtra_2.3    tibble_1.4.2

**Comment by MatsuuraKentaro** [comment]
エラーの報告ありがとうございます！

stan 2.11までは実行できたことを確認したのですが、たしかに現状のバージョンではそのようなエラーが出て、おっしゃるように`Y`できちんと場合分けしないと推定できませんでした（`q`の範囲は`real<lower=0, upper=1> q;`でいけると思います）。

開発元に簡単に確認するので少しお待ちいただいてよろしいでしょうか？すみません。

**Comment by takeshou** [comment]
早速の返信ありがとうございます！
特に急いでいるわけではありませんので、大丈夫です。
qの範囲は、同僚もそう言っていました。僕の投稿ミスです。すみませんでした。

**Comment by MatsuuraKentaro** [comment]
本家に聞いていますが、どうもwindows特有の現象らしく、対応が遅れています。
https://discourse.mc-stan.org/t/has-the-behavior-of-log-sum-exp-changed/5996
たしかにWindows 7, 10で試すと上記のエラーが出ますが、Linuxでは出ませんでした。本家の対応をゆっくり待ちたいと思います。それまではお手数かけて申し訳ないですが、`Y` の値で場合分けしたモデルで対応してくださいますでしょうか。

**Comment by takeshou** [comment]
ご確認ありがとうございます。
Windows固有の問題だったんですね。
こういう形で対応するのは全く問題ありません。

ただ、この対応方法で間違っていないか確認したかったのと、
ひょっとして何かスマートな方法がないかと思い質問させていただきました。

いいことかどうかは別として、
こういったバッドノウハウも勉強にはなるなぁと感じた次第です。
今後ともどうぞよろしくお願いいたします。

**Comment by MatsuuraKentaro** [comment]
こちらの件、Windowsでもrstan 2.18.1にしたら実行できるようになりました。
rstan 2.18にアップデートすると、コンパイル時に `C++14 standard requested but CXX14 is not defined
` と表示される場合には、 `<Rのフォルダ>\etc\x64\Makeconf` の84-85行目を以下に変更する必要があります。もしバージョンアップをするタイミングがあればお試しくださいませ。

```
CXX14 = $(BINPREF)g++ $(M_ARCH)
CXX14FLAGS = -O2 -Wall $(DEBUGFLAG) -mtune=generic
```

**Comment by takeshou** [comment]
ご連絡、ありがとうございます。
早速試してみたいと思います。

あと、エラーの対処も助かりました。
まさに上記の表示があり、困っていました。
時間がとれ次第、やってみたいと思います。

どうもありがとうございました。

こちらのissueは一旦クローズさせていただきます。
丁寧なご対応ありがとうございました。
