### ISSUE TITLE
ベータ関数の数式に誤りはありませんか？

### ISSUE THREAD

**Issue by tomoyuki-nohara-abeja** [MatsuuraKentaro/RStanBook#7]
P84のベータ関数

B(a, b) = gamma(a+b) / (gamma(a) * gamma(b))

とありますが

B(a, b) = (gamma(a) * gamma(b)) /gamma(a+b)

ではないでしょうか？

参照
https://ja.wikipedia.org/wiki/%E3%83%99%E3%83%BC%E3%82%BF%E9%96%A2%E6%95%B0

**Comment by MatsuuraKentaro** [comment]
ご指摘ありがとうございます。おっしゃる通りですね。正誤表に載せ、次回以降の増刷で修正させていただきます。

**Comment by tomoyuki-nohara-abeja** [comment]
ご対応ありがとうございます。とても素晴らしい本だと感じていますので失礼ながらご指摘させていただきました。今後とも勉強させて頂きます。

**Comment by MatsuuraKentaro** [comment]
嬉しいです！正誤表に掲載しました。ありがとうございました。
